### ISSUE TITLE
Fix or remove feeds

### ISSUE THREAD

**Issue by bogaert** [snowplow/snowplowanalytics.com#297] opened 2017-09-21 10:40 UTC
From Simon:

>These feed URLs are broken on your site:
>`<link href="http://snowplowanalytics.com" type="application/atom+xml" rel="alternate" title="Sitewide ATOM Feed">`
>`<link href="http://snowplowanalytics.com" type="application/rss+xml" rel="alternate" title="Sitewide RSS Feed">`

**Comment by jbeemster** [comment] 2017-09-21 10:50
To add to this the current atom link (https://snowplowanalytics.com/atom.xml) no longer correctly HREFs any of the blog posts:

> href="/blog/2017/08/30/snowplow-mini-0.3.0-released#out-of-the-box-ssl"

Should be:

> href="http://snowplowanalytics.com/blog/2017/08/30/snowplow-mini-0.3.0-released#out-of-the-box-ssl"

**Comment by yalisassoon** [comment] 2017-09-21 14:13
We'll get these fixed. I can't however see where we're advertising / linking to them? (Would like to remove them until they're fixed.)

**Comment by jorgemgoncalves** [comment] 2017-10-03 11:54
Hi @yalisassoon @bogaert @jbeemster, we have implemented a fix for this issue although we would like to point out some possible misusage of site variables.

Jekyll RSS Feed and Sitemap build use the **_config.yml** `production_url` var. This is referenced in the **sitemap.txt** front matter comment. Because we didn't find the variable `production_url` we changed it to just `url`.

Our fix confirmed that **sitemap.txt,** **rss.xml** and **atom.xml** are build with correct absolute path. Although in the local build `site.url` is configured to be `snowplowanalytics.com` we have confirmed that this var prints out `0.0.0.0:4000`. Please make sure that this doesn't happen in the remote build. 

Please notice that this commit was posted on the new Community Page branch. My pull request should reflect these two changes.

**Comment by yalisassoon** [comment] 2017-10-06 13:53
Thanks @jorgemgoncalves ! 

It looks like there's an issue with a stray character on both the atom feeds? 

![image](https://user-images.githubusercontent.com/201147/31280982-209581fe-aa7c-11e7-889c-ad8186f06152.png)

The sitemap looks good!

**Comment by jorgemgoncalves** [comment] 2017-10-27 12:22
Hi @yalisassoon @bogaert @jbeemster, the #356 merge to QA fixed the RSS feed issue.

We've also added a Feed entry limiter in the _config.yml file which allows you to select the total number of posts that appear. If you choose to remove the value and they will all appear. 

Please give me your feedback so that I request a pull to Next.

Cheers.

**Closed** 2017-11-14 10:28 UTC
