### ISSUE TITLE
Include more Call to Action on the website

### ISSUE THREAD

**Issue by jorgemgoncalves** [snowplow/snowplowanalytics.com#293] opened 2017-09-20 09:31 UTC

**Comment by yalisassoon** [comment] 2018-02-22 08:45
We're starting to write a lot of content geared towards driving awareness and interest at Snowplow on our blog. It would be graet if we could develop a set of calls to actions (e.g. big buttons / banners) to encourage people to e.g. sign up to our mailing list, or book a demo that we can pop on any page e.g. at the top or bottom of the blog post. The links could be something like this:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/201147/36528338-a6e8c246-17ac-11e8-99bd-b88f96f9b924.png">

But maybe coloured to draw more attention.

**Comment by yalisassoon** [comment] 2018-03-08 13:11
Duplicate of https://github.com/snowplow/snowplowanalytics.com/issues/511 - closing

**Closed by yalisassoon** 2018-03-08 13:11 UTC
